// mainwindow.cpp
#include "mainwindow.h"
#include "ui_mainwindow.h"


MainWindow::MainWindow(QWidget *parent)
            :QMainWindow(parent), ui(new Ui::MainWindow)
{
    /*
        new Ui::MainWindow: dynamicaly creates the object of Ui::MainWindow,
        which was generated by mainwindow.ui in Qt Creator.
        this object contans interface and all their elements
     */
    ui->setupUi(this);
}

MainWindow::~MainWindow(){
    delete ui;
}


